name: Generate Snake SVG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation SVG
        uses: liady/snake-animation@main
        with:
          username: NatanSrsDev
          output_path: output/snake.svg

      - name: Commit generated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "Update snake.svg"
          git push
